### PR TITLE
feat(catalog): re-build catalog if trigger has no records

### PR DESCRIPTION
**Pull request by RomainMuller**
This allows to easily re-create the catalog from scratch if that is
ever needed. It might be useful to schedule this every so often, just
to ensure the catalog file stays healthy (but it is not done in the
context of this change).

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by eladb — COMMENTED** [review]
Can we simplify and always build the catalog every time? What are we optimizing here and why?

**Comment by RomainMuller** [comment]
> Can we simplify and always build the catalog every time? What are we optimizing here and why?

I guess this is to maximise catalog refresh speed... The current process can be a bit slow as it involves downloading a ton of tarballs, for some reason (I'd look into that later).

**Comment by eladb** [comment]
> downloading a ton of tarballs

?? what?

**Comment by RomainMuller** [comment]
> > downloading a ton of tarballs
> 
> ?? what?

Yes I was horrified at the discovery... This is so inefficient... But this would be a somewhat larger change than the one proposed here... (And I intend on making that, too... but I also would like to be able to rebuild the catalog file without deleting it first).

https://github.com/cdklabs/construct-hub/blob/b16558aec791df0de73cb88c1a77bd51087d8848/src/backend/catalog-builder/catalog-builder.lambda.ts#L135-L200

**Comment by eladb** [comment]
Superseded by #174

**Pull request closed without merging**
